
function CountryArr() {
    const countryArr = [
        {value: 'af',label:'Afghanistan',countrycode:+93,format:null},
        {value: 'al',label:'Albania',countrycode:+355,format:null},
        {value: 'dz',label:'Algeria',countrycode:+213,format:null},
        {value: 'ad',label:'Andorra',countrycode:+376,format:null},
        {value: 'ao',label:'Angola',countrycode:+244,format:null},
        {value: 'ag',label:'Antigua and Barbuda',countrycode:+1268,format:null},
        {value: 'ar',label:'Argentina',countrycode:+54,format:'+54 (..) ........'},
        {value: 'am',label:'Armenia',countrycode:+374,format:'+374 .. ......'},
        {value: 'aw',label:'Aruba',countrycode:+297,format:null},
        {value: 'au',label:'Australia',countrycode:+61,format:'+61 (..) .... ....'},
        {value: 'at',label:'Austria',countrycode:+43,format:null},
        {value: 'az',label:'Azerbaijan',countrycode:+994,format:'+994 (..) ... .. ..'},
        {value: 'bs',label:'Bahamas',countrycode:+1242,format:null},
        {value: 'bh',label:'Bahrain',countrycode:+973,format:null},
        {value: 'bd',label:'Bangladesh',countrycode:+880,format:null},
        {value: 'bb',label:'Barbados',countrycode:+1246,format:null},
        {value: 'by',label:'Belarus',countrycode:+375,format:'+375 (..) ... .. ..'},
        {value: 'be',label:'Belgium',countrycode:+32,format:'+32 ... .. .. ..'},
        {value: 'bz',label:'Belize',countrycode:+501,format:null},
        {value: 'bj',label:'Benin',countrycode:+229,format:null},
        {value: 'bt',label:'Bhutan',countrycode:+975,format:null},
        {value: 'bo',label:'Bolivia',countrycode:+591,format:null},
        {value: 'ba',label:'Bosnia and Herzegovina',countrycode:+387,format:null},
        {value: 'bw',label:'Botswana',countrycode:+267,format:null},
        {value: 'br',label:'Brazil',countrycode:+55,format:'+55 (..) .........'},
        {value: 'io',label:'British Indian Ocean Territory',countrycode:+246,format:null},
        {value: 'bn',label:'Brunei',countrycode:+673,format:null},
        {value: 'bg',label:'Bulgaria',countrycode:+359,format:null},
        {value: 'bf',label:'Burkina Faso',countrycode:+226,format:null},
        {value: 'bi',label:'Burundi',countrycode:+257,format:null},
        {value: 'kh',label:'Cambodia',countrycode:+855,format:null},
        {value: 'cm',label:'Cameroon',countrycode:+237,format:null},
        {value: 'ca',label:'Canada',countrycode:+1,format:'+1 (...) ...-....'},
        {value: 'cv',label:'Cape Verde',countrycode:+238,format:null},
        {value: 'bq',label:'Caribbean Netherlands',countrycode:+599,format:null},
        {value: 'cf',label:'Central African Republic',countrycode:+236,format:null},
        {value: 'td',label:'Chad',countrycode:+235,format:null},
        {value: 'cl',label:'Chile',countrycode:+56,format:null},
        {value: 'cn',label:'China',countrycode:+86,format:'+86 ..-.........'},
        {value: 'co',label:'Colombia',countrycode:+57,format:'+57 ... ... ....'},
        {value: 'km',label:'Comoros',countrycode:+269,format:null},
        {value: 'cd',label:'Congo',countrycode:+243,format:null},
        {value: 'cg',label:'Congo',countrycode:+242,format:null},
        {value: 'cr',label:'Costa Rica',countrycode:+506,format:'+506 ....-....'},
        {value: 'ci',label:'Côte d’Ivoire',countrycode:+225,format:'+225 .. .. .. ..'},
        {value: 'hr',label:'Croatia',countrycode:+385,format:null},
        {value: 'cu',label:'Cuba',countrycode:+53,format:null},
        {value: 'cw',label:'Curaçao',countrycode:+599,format:null},
        {value: 'cy',label:'Cyprus',countrycode:+357,format:'+357 .. ......'},
        {value: 'cz',label:'Czech Republic',countrycode:+420,format:'+420 ... ... ...'},
        {value: 'dk',label:'Denmark',countrycode:+45,format:'+45 .. .. .. ..'},
        {value: 'dj',label:'Djibouti',countrycode:+253,format:null},
        {value: 'dm',label:'Dominica',countrycode:+1767,format:null},
        {value: 'do',label:'Dominican Republic',countrycode:+1,format:null},
        {value: 'ec',label:'Ecuador',countrycode:+593,format:null},
        {value: 'eg',label:'Egypt',countrycode:+20,format:null},
        {value: 'sv',label:'El Salvador',countrycode:+503,format:'+503 ....-....'},
        {value: 'gq',label:'Equatorial Guinea',countrycode:+240,format:null},
        {value: 'er',label:'Eritrea',countrycode:+291,format:null},
        {value: 'ee',label:'Estonia',countrycode:+372,format:'+372 .... ......'},
        {value: 'et',label:'Ethiopia',countrycode:+251,format:null},
        {value: 'fj',label:'Fiji',countrycode:+679,format:null},
        {value: 'fi',label:'Finland',countrycode:+358,format:'+358 .. ... .. ..'},
        {value: 'fr',label:'France',countrycode:+33,format:'+33 . .. .. .. ..'},
        {value: 'gf',label:'French Guiana',countrycode:+594,format:null},
        {value: 'pf',label:'French Polynesia',countrycode:+689,format:null},
        {value: 'ga',label:'Gabon',countrycode:+241,format:null},
        {value: 'gm',label:'Gambia',countrycode:+220,format:null},
        {value: 'ge',label:'Georgia',countrycode:+995,format:null},
        {value: 'de',label:'Germany',countrycode:+49,format:'+49 .... ........'},
        {value: 'gh',label:'Ghana',countrycode:+233,format:null},
        {value: 'gr',label:'Greece',countrycode:+30,format:null},
        {value: 'gd',label:'Grenada',countrycode:+1473,format:null},
        {value: 'gp',label:'Guadeloupe',countrycode:+590,format:null},
        {value: 'gu',label:'Guam',countrycode:+1671,format:null},
        {value: 'gt',label:'Guatemala',countrycode:+502,format:'+502 ....-....'},
        {value: 'gn',label:'Guinea',countrycode:+224,format:null},
        {value: 'gw',label:'Guinea-Bissau',countrycode:+245,format:null},
        {value: 'gy',label:'Guyana',countrycode:+592,format:null},
        {value: 'ht',label:'Haiti',countrycode:+509,format:'+509 ....-....'},
        {value: 'hn',label:'Honduras',countrycode:+504,format:null},
        {value: 'hk',label:'Hong Kong',countrycode:+852,format:'+852 .... ....'},
        {value: 'hu',label:'Hungary',countrycode:+36,format:null},
        {value: 'is',label:'Iceland',countrycode:+354,format:'+354 ... ....'},
        {value: 'in',label:'India',countrycode:+91,format:'+91 .....-.....'},
        {value: 'id',label:'Indonesia',countrycode:+62,format:null},
        {value: 'ir',label:'Iran',countrycode:+98,format:'+98 ... ... ....'},
        {value: 'iq',label:'Iraq',countrycode:+964,format:null},
        {value: 'ie',label:'Ireland',countrycode:+353,format:'+353 .. .......'},
        {value: 'il',label:'Israel',countrycode:+972,format:'+972 ... ... ....'},
        {value: 'it',label:'Italy',countrycode:+39,format:'+39 ... .......'},
        {value: 'jm',label:'Jamaica',countrycode:+1876,format:null},
        {value: 'jp',label:'Japan',countrycode:+81,format:'+81 .. .... ....'},
        {value: 'jo',label:'Jordan',countrycode:+962,format:null},
        {value: 'kz',label:'Kazakhstan',countrycode:+7,format:'+7 ... ...-..-..'},
        {value: 'ke',label:'Kenya',countrycode:+254,format:null},
        {value: 'ki',label:'Kiribati',countrycode:+686,format:null},
        {value: 'xk',label:'Kosovo',countrycode:+383,format:null},
        {value: 'kw',label:'Kuwait',countrycode:+965,format:null},
        {value: 'kg',label:'Kyrgyzstan',countrycode:+996,format:'+996 ... ... ...'},
        {value: 'la',label:'Laos',countrycode:+856,format:null},
        {value: 'lv',label:'Latvia',countrycode:+371,format:'+371 .. ... ...'},
        {value: 'lb',label:'Lebanon',countrycode:+961,format:null},
        {value: 'ls',label:'Lesotho',countrycode:+266,format:null},
        {value: 'lr',label:'Liberia',countrycode:+231,format:null},
        {value: 'ly',label:'Libya',countrycode:+218,format:null},
        {value: 'li',label:'Liechtenstein',countrycode:+423,format:null},
        {value: 'lt',label:'Lithuania',countrycode:+370,format:null},
        {value: 'lu',label:'Luxembourg',countrycode:+352,format:null},
        {value: 'mo',label:'Macau',countrycode:+853,format:null},
        {value: 'mk',label:'Macedonia',countrycode:+389,format:null},
        {value: 'mg',label:'Madagascar',countrycode:+261,format:null},
        {value: 'mw',label:'Malawi',countrycode:+265,format:null},
        {value: 'my',label:'Malaysia',countrycode:+60,format:'+60 ..-....-....'},
        {value: 'mv',label:'Maldives',countrycode:+960,format:null},
        {value: 'ml',label:'Mali',countrycode:+223,format:null},
        {value: 'mt',label:'Malta',countrycode:+356,format:null},
        {value: 'mh',label:'Marshall Islands',countrycode:+692,format:null},
        {value: 'mq',label:'Martinique',countrycode:+596,format:null},
        {value: 'mr',label:'Mauritania',countrycode:+222,format:null},
        {value: 'mu',label:'Mauritius',countrycode:+230,format:null},
        {value: 'mx',label:'Mexico',countrycode:+52,format:'+52 ... ... ....'},
        {value: 'fm',label:'Micronesia',countrycode:+691,format:null},
        {value: 'md',label:'Moldova',countrycode:+373,format:'+373 (..) ..-..-..'},
        {value: 'mc',label:'Monaco',countrycode:+377,format:null},
        {value: 'mn',label:'Mongolia',countrycode:+976,format:null},
        {value: 'me',label:'Montenegro',countrycode:+382,format:null},
        {value: 'ma',label:'Morocco',countrycode:+212,format:null},
        {value: 'mz',label:'Mozambique',countrycode:+258,format:null},
        {value: 'mm',label:'Myanmar',countrycode:+95,format:null},
        {value: 'na',label:'Namibia',countrycode:+264,format:null},
        {value: 'nr',label:'Nauru',countrycode:+674,format:null},
        {value: 'np',label:'Nepal',countrycode:+977,format:null},
        {value: 'nl',label:'Netherlands',countrycode:+31,format:'+31 .. ........'},
        {value: 'nc',label:'New Caledonia',countrycode:+687,format:null},
        {value: 'nz',label:'New Zealand',countrycode:+64,format:'+64 ...-...-....'},
        {value: 'ni',label:'Nicaragua',countrycode:+505,format:null},
        {value: 'ne',label:'Niger',countrycode:+227,format:null},
        {value: 'ng',label:'Nigeria',countrycode:+234,format:null},
        {value: 'kp',label:'North Korea',countrycode:+850,format:null},
        {value: 'no',label:'Norway',countrycode:+47,format:'+47 ... .. ...'},
        {value: 'om',label:'Oman',countrycode:+968,format:null},
        {value: 'pk',label:'Pakistan',countrycode:+92,format:'+92 ...-.......'},
        {value: 'pw',label:'Palau',countrycode:+680,format:null},
        {value: 'ps',label:'Palestine',countrycode:+970,format:null},
        {value: 'pa',label:'Panama',countrycode:+507,format:null},
        {value: 'pg',label:'Papua New Guinea',countrycode:+675,format:null},
        {value: 'py',label:'Paraguay',countrycode:+595,format:null},
        {value: 'pe',label:'Peru',countrycode:+51,format:null},
        {value: 'ph',label:'Philippines',countrycode:+63,format:'+63 .... .......'},
        {value: 'pl',label:'Poland',countrycode:+48,format:'+48 ...-...-...'},
        {value: 'pt',label:'Portugal',countrycode:+351,format:null},
        {value: 'pr',label:'Puerto Rico',countrycode:+1,format:null},
        {value: 'qa',label:'Qatar',countrycode:+974,format:null},
        {value: 're',label:'Réunion',countrycode:+262,format:null},
        {value: 'ro',label:'Romania',countrycode:+40,format:null},
        {value: 'ru',label:'Russia',countrycode:+7,format:'+7 (...) ...-..-..'},
        {value: 'rw',label:'Rwanda',countrycode:+250,format:null},
        {value: 'kn',label:'Saint Kitts and Nevis',countrycode:+1869,format:null},
        {value: 'lc',label:'Saint Lucia',countrycode:+1758,format:null},
        {value: 'vc',label:'Saint Vincent and the Grenadines',countrycode:+1784,format:null},
        {value: 'ws',label:'Samoa',countrycode:+685,format:null},
        {value: 'sm',label:'San Marino',countrycode:+378,format:null},
        {value: 'st',label:'São Tomé and Príncipe',countrycode:+239,format:null},
        {value: 'sa',label:'Saudi Arabia',countrycode:+966,format:null},
        {value: 'sn',label:'Senegal',countrycode:+221,format:null},
        {value: 'rs',label:'Serbia',countrycode:+381,format:null},
        {value: 'sc',label:'Seychelles',countrycode:+248,format:null},
        {value: 'sl',label:'Sierra Leone',countrycode:+232,format:null},
        {value: 'sg',label:'Singapore',countrycode:+65,format:'+65 ....-....'},
        {value: 'sk',label:'Slovakia',countrycode:+421,format:null},
        {value: 'si',label:'Slovenia',countrycode:+386,format:null},
        {value: 'sb',label:'Solomon Islands',countrycode:+677,format:null},
        {value: 'so',label:'Somalia',countrycode:+252,format:null},
        {value: 'za',label:'South Africa',countrycode:+27,format:null},
        {value: 'kr',label:'South Korea',countrycode:+82,format:'+82 ... .... ....'},
        {value: 'ss',label:'South Sudan',countrycode:+211,format:null},
        {value: 'es',label:'Spain',countrycode:+34,format:'+34 ... ... ...'},
        {value: 'lk',label:'Sri Lanka',countrycode:+94,format:null},
        {value: 'sd',label:'Sudan',countrycode:+249,format:null},
        {value: 'sr',label:'Suriname',countrycode:+597,format:null},
        {value: 'sz',label:'Swaziland',countrycode:+268,format:null},
        {value: 'se',label:'Sweden',countrycode:+46,format:'+46 (...) ...-...'},
        {value: 'ch',label:'Switzerland',countrycode:+41,format:'+41 .. ... .. ..'},
        {value: 'sy',label:'Syria',countrycode:+963,format:null},
        {value: 'tw',label:'Taiwan',countrycode:+886,format:null},
        {value: 'tj',label:'Tajikistan',countrycode:+992,format:null},
        {value: 'tz',label:'Tanzania',countrycode:+255,format:null},
        {value: 'th',label:'Thailand',countrycode:+66,format:null},
        {value: 'tl',label:'Timor-Leste',countrycode:+670,format:null},
        {value: 'tg',label:'Togo',countrycode:+228,format:null},
        {value: 'to',label:'Tonga',countrycode:+676,format:null},
        {value: 'tt',label:'Trinidad and Tobago',countrycode:+1868,format:null},
        {value: 'tn',label:'Tunisia',countrycode:+216,format:null},
        {value: 'tr',label:'Turkey',countrycode:+90,format:'+90 ... ... .. ..'},
        {value: 'tm',label:'Turkmenistan',countrycode:+993,format:null},
        {value: 'tv',label:'Tuvalu',countrycode:+688,format:null},
        {value: 'ug',label:'Uganda',countrycode:+256,format:null},
        {value: 'ua',label:'Ukraine',countrycode:+380,format:'+380 (..) ... .. ..'},
        {value: 'ae',label:'United Arab Emirates',countrycode:+971,format:null},
        {value: 'gb',label:'United Kingdom',countrycode:+44,format:'+44 .... ......'},
        {value: 'us',label:'United States',countrycode:+1,format:'+1 (...) ...-....'},
        {value: 'uy',label:'Uruguay',countrycode:+598,format:null},
        {value: 'uz',label:'Uzbekistan',countrycode:+998,format:'+998 .. ... .. ..'},
        {value: 'vu',label:'Vanuatu',countrycode:+678,format:null},
        {value: 'va',label:'Vatican City',countrycode:+39,format:'+39 .. .... ....'},
        {value: 've',label:'Venezuela',countrycode:+58,format:null},
        {value: 'vn',label:'Vietnam',countrycode:+84,format:null},
        {value: 'ye',label:'Yemen',countrycode:+967,format:null},
        {value: 'zm',label:'Zambia',countrycode:+260,format:null},
        {value: 'zw',label:'Zimbabwe',countrycode:+263,format:null},
    ]

    return countryArr;
}

export default CountryArr
